feat: move slow jumps and jumpfix to so3g
simonsobs/sotodlib pull request #1081
Opened 2024-12-26 19:08 UTC by skhrg

2025-01-13 09:53 UTC, kwolz reviewed
I've looked into the changes. I have only two small comments for my ease of understanding, otherwise it looks good to me.

2025-01-13 16:11 UTC, skhrg commented on sotodlib/tod_ops/jumps.py
> +    jumps = cast(RangesMatrix, jumps)
Honestly that was just to make my typechecker shut up...

2025-01-14 02:14 UTC, skhrg commented on tests/test_tod_ops.py
> +        self.assertTrue(ptp_fix < 1.1*ptp_orig)
Yup, upped the buffer in the test to be conservative so that things never fail in CI. But also I set the PRNG key so I think that is unneeded.

2025-01-15 16:05 UTC, mmccrackan reviewed
I think this looks fine other than the failing checks.

2025-01-15 16:59 UTC, skhrg commented
https://github.com/simonsobs/so3g/pull/196 is now merged so this should be good to go very soon

2025-01-15 17:19 UTC, mhasself commented on sotodlib/tod_ops/jumps.py
> +    block_minmax,
One way to create some backwards-compatibility is to not import these by name.  Just import so3g.  Then the code will crash when you try to use those functions, rather than when you try to import them.

As written now, everyone's installation will break, if they try to use _anything_ from `sotodlib.tod_ops`, unless they've updated so3g.

2025-02-11 13:45 UTC, skhrg commented
Now that the new so3g is out can someone approve this?

2025-02-11 14:29 UTC, mmccrackan approved these changes

2025-02-11 14:42 UTC, mhasself requested changes
Minor comments ... looking forward to seeing this out in the wild.

2025-02-11 14:42 UTC, mhasself commented on sotodlib/tod_ops/jumps.py
> +from pixell.utils import moveaxis
Replace the one remaining moveaxis with np.moveaxis.

2025-02-11 14:42 UTC, mhasself commented on sotodlib/tod_ops/jumps.py
> +        x_fixed = np.ascontiguousarray(x_fixed)
To reduce unnecessary reallocations, make use of `np.asarray`.  To do these two lines, for example, you can just:  `x_fixed = np.asarray(x, order='C', copy=True)`

2025-02-11 14:42 UTC, mhasself commented on sotodlib/tod_ops/jumps.py
> +    heights = np.ascontiguousarray(heights)
```
# This will only copy if needed for dtype/order.
heights = np.asarray(heights, dtype=x.dtype, order='C')
```

2025-02-11 14:42 UTC, mhasself commented on sotodlib/tod_ops/jumps.py
> +    x = np.ascontiguousarray(x)
If user requested inplace, and x is not contiguous, then the change won't be in-place.  So you need to check for that.

For example
```
x = np.asarray(x, order='C', copy=(False if inplace else None))
```

2025-02-12 13:27 UTC, skhrg commented on sotodlib/tod_ops/jumps.py
> +    x = np.ascontiguousarray(x)
Do we really want to raise a value error if inplace is requested but the array is not contiguous?
I could instead raise a warning, make a copy, and then copy back into the original `x` later. But that may be babying the user too much.

2025-02-12 13:34 UTC, skhrg commented on sotodlib/tod_ops/jumps.py
> +    x = np.ascontiguousarray(x)
Actually assuming we want to raise the error in that case is the most correct block something like:

```
x_fixed = np.asarray(np.atleast_2d(x), order="C", copy=(False if inplace else None))
```

That way the cases are as follows:

* in place and already contiguous -> `x_fixed` just references `x`
* in place and not contiguous -> `ValueError`
* no in place and already contiguous -> `x_fixed` is a copy of `x`
* no in place and not contiguous -> `x_fixed` is a contiguous copy of `x`

Does that make sense?

2025-02-12 14:20 UTC, mhasself commented on sotodlib/tod_ops/jumps.py
> +    x = np.ascontiguousarray(x)
W.r.t. "no in place and already contiguous -> x_fixed is a copy of x" -- actually not true; `np.asarray(... copy=None)` will not copy if it doesn't need to.

Another way to approach this, to minimize copies and simplify logic:
- Apply all the conversions you need to get `x_fixed`, minimizing copies where possible.
- *Check* whether you ended up making a copy, or not -- `fixed_is_a_copy = np.may_share_memory(x, x_fixed)`
- Take different actions depending on `(fixed_is_a_copy, inplace)`.

I'm ok with your suggestion of making a copy and then updating x at the end.

The reason to ValueError would be that "inplace" is sometimes used not just to compress code, but to minimize copying of the data -- it's sort of implied that doing things inplace will use less RAM, less time.  But I think printing a warning is sufficient to help super-optimizers tweak things up.

2025-02-12 16:49 UTC, skhrg commented
Tests failing with ` TypeError: asarray() got an unexpected keyword argument 'copy'`, looks like that was added in numpy 2.0.0 (and I believe the PR for numpy 2.0 support in so3g is not yet ready).

I'll redo some logic to sidestep this... but hopefully in the future we can switch to it

2025-02-12 18:56 UTC, skhrg commented
...the problem with devving on both my laptop and site computing is sometimes I don't push all my fixes.
Should pass now.

2025-02-12 21:30 UTC, mhasself approved these changes

2025-02-13 14:04 UTC, merged

2025-02-19 14:38 UTC, msilvafe commented
@skhrg does this close out Issue #975 ?