Context changes to support on-the-fly detdb
simonsobs/sotodlib pull request #242
Opened 2022-03-23 14:38 UTC by jseibert575

This PR adds functionality to Context to build the obs_detdb, a DetDb-like object that is constructed upon calling either get_obs or get_meta (or check_meta) after providing a specific obs_id. It populates the attribute `ctx.obs_detdb` and leaves `ctx.detdb` alone to make clear that the object is not the same as a traditional DetDb, though it does still belong to that class. 

Adds a hook, living in the load_smurf module, that is called with key `before-load-obs` after the obs_id is initialized. Here is an example Context file:

```
tags:
  g3tsmurf_dir: '/mnt/so1/users/kmharrin/smurf_context'

obsfiledb: '{g3tsmurf_dir}/latrt_db_v4.db'
obsdb: '{g3tsmurf_dir}/latrt_db_v4.db'

imports:
  - sotodlib.io.load_smurf

obs_loader_type: 'g3tsmurf'

context_hooks: obs_detdb_load
```
Notice that the detdb key isn't included here.

I've tested this using a few obs_ids and haven't had any issues yet. I've also checked the metadata loading which does work, but am not including that in the example Context file because there are some bugs that are related to the construction of the CalDb I'm loading, having nothing to do with the changes addressed in this PR.

2022-03-23 21:31 UTC, kmharrington commented on sotodlib/core/context.py
> +        self._call_hook('before-load-obs', obs_id=obs_id,
should probably include dets as something passed to this hook

2022-03-23 21:32 UTC, kmharrington commented on sotodlib/io/load_smurf.py
> +    return load_file(flist, dets, samples=samples, obsfiledb=db, short_labels=False)
sorry I messed that up!

2022-04-01 16:36 UTC, mhasself requested changes
Sorry for the delay on the review.  This looks good but I have one request:

You are calling the same hook, "before-load-obs", in 3 different places.  Only one of those might legitimately be thought of as "before the observation is loaded".  But clearly you want to do the same thing in each case: provide an observation-specific detdb.  So how about we change the name of this hook to "before-use-detdb"?

2022-04-22 13:48 UTC, mhasself approved these changes
Great!

2022-04-22 17:22 UTC, merged