AxisManager utility functions
simonsobs/sotodlib pull request #270
Opened 2022-06-10 19:00 UTC by jlashner

A couple of useful axismanager functions implemented in sodetlib usage. Katie said a few may be more generally applicable so I'm copying them here.

If these are merged in I'll remove them from sodetlib.

2022-06-12 18:30 UTC, mhasself requested changes
One could see either of these getting into the class itself (restrict_to_times would need to be a bit more general; restrict_by_value or something).  But good to have them in here.

Please add basic smoke testing for these to tests/test_core.py

2022-06-12 18:30 UTC, mhasself commented on sotodlib/core/axisman_util.py
> +    """Exception for when cannot restrict AxisManger properly"""
AxisManager.

2022-06-14 00:47 UTC, jlashner commented
Thanks for the review! Comments implemented and tests added

2022-07-01 02:50 UTC, mhasself approved these changes
Sorry for the slow follow-up.  Thanks for the changes.

2022-07-05 11:30 UTC, merged