HWP angle calculator with quad enable option
simonsobs/sotodlib pull request #317
Opened 2022-10-25 12:28 UTC by yukisakurai

There is a hardware issue that makes frequently flipping quad value (rotation direction) in P10R1. This PR adds an option to enable quad or not in config file. This option should be basically on if hwp readout is working correctly, but it is useful for lab. testing and debug.
You need to include `enable_quad: False` to config yaml file if you want to turn off it.
Also I modified reference slit finding module to fix hwp_rate and updated docs.  
(This PR has been overwritten from RP#315.)

**Angle solution**
![image](https://user-images.githubusercontent.com/10991568/197772440-e99c6414-1269-4dc4-860c-11b378199ba9.png)
![image](https://user-images.githubusercontent.com/10991568/197772393-da2c7114-d85b-4196-9e2d-31a9e42060bc.png)
**hwp_rate**
![image](https://user-images.githubusercontent.com/10991568/197771400-fb447108-3bf7-4e3a-878a-db2ce393cc0b.png)
![image](https://user-images.githubusercontent.com/10991568/197771525-b8b9d42c-e3b3-4f01-8709-647ca4069e63.png)

2022-10-25 14:41 UTC, kmharrington requested changes
I like the change with letting quad be fixed from the config file.

My change request is the commit history, it looks like you copied the lines of code from PR#315 into this and re-commited? A better way to do it is to merge that branch into yours. I believe that would be `git merge frame-ify-hwp hwp`. Then we'd be 100% sure everything from PR#315 was copied over and git would understand how to make the final merge. As is we're going to get merge conflicts when we try and merge both of these PRs. 

Could you remove your commit where you added in the #315 changes and merge the branch instead? Thanks!

2022-10-25 22:25 UTC, kmharrington commented
Just an update, since we've merged #315  you should be able to rebase this branch off of master, then we'll be good to go.

2022-10-25 23:38 UTC, yukisakurai commented
I rebased this branch from master and added the updates.

2022-10-26 05:47 UTC, mhasself approved these changes
The rebase against master looks like it was using a stale version of that branch.  I think you need to "git fetch", then "git rebase origin/master" and "git push --force".  Approving but please fix this first.

In cases where quad is disabled, the direction of spin is assumed to be positive ... but perhaps the direction to assume should be a configuration parameter?  Or at least some way to control it?  I defer to your experience on this though.

2022-10-26 07:48 UTC, yukisakurai commented
Thank you guys for your suggestions.
I processed "git fetch" → "git rebase origin/master" → "git push --force". There is no conflict now.
I have made it possible to force the rotation direction from the config.
`enable_quad` → `force_quad` (0 or 1 or -1)
ex) `force_quad: -1` if you want to force negative rotation direction

2022-10-26 14:25 UTC, kmharrington approved these changes
looks good, let's try it!

2022-10-26 14:45 UTC, merged