Bookbinder update
simonsobs/sotodlib pull request #367
Opened 2023-01-06 16:48 UTC by guanyilun

2023-01-06 19:30 UTC, kmharrington commented on sotodlib/io/bookbinder.py
>  def smurf_reader(filename):
We shouldn't use this. This function is identical to `spt3g.core.G3File`.

2023-01-12 14:07 UTC, guanyilun commented
OK, I think this is PR at a good place to get merged.

2023-01-12 17:10 UTC, kmharrington commented
Hi @guanyilun  could you update your first PR comment with an overview of what's changed in this PR and what to look for in the code?

2023-01-12 17:44 UTC, kmharrington requested changes
Ok, I haven't fully understood the details of bookbinder yet but I don't see anything obviously wrong. Please add a summary of the PR (for history's sake) and 2 inline things.

2023-01-13 16:44 UTC, kmharrington approved these changes
thanks! I'm trying to re-run the tests to see if that fixes the errors (seems like a connection thing) if those pass then we're good to merge.

2023-01-13 18:59 UTC, merged