Simulated focalplane spacing
simonsobs/sotodlib pull request #505
Opened 2023-07-17 19:44 UTC by tskisner

This PR is the matching one for the [upstream PR in toast](https://github.com/hpc4cmb/toast/pull/674).  This ensures that focalplane layout widths are always given in terms of pixel centers rather than field of view.

2023-07-25 20:31 UTC, tskisner commented
This work attempts to fix some issues with the synthetic focalplane layout, and also move some common helper functions upstream to reduce future maintenance burden.  Below is a detailed examination of the code in this PR (and the corresponding toast PR).  Note that there are differences when compared to current toast and current sotodlib master, so it is important to verify that the current code is correct.

**NOTE:  All plots in boresight X/Y coordinates looking from sky into the instrument**.  Recall that the positive "X" axis points "down" in elevation.

# LAT

First looking at the LAT layout.  Tube spacing is 359.6mm with a platescale of 0.00495 deg/mm.  In a hexagonal packing scheme, we would expect the LF tube to be located at Xi = (2 * tube_spacing) / (sqrt(3) / 2), which corresponds to +3.08 degrees.  The spacing in Eta between the other tubes should be 1.78 degrees.  These are supported by the overall plot here.
![lat pdf](https://github.com/simonsobs/sotodlib/assets/84221/0df76515-e9e0-4b36-861f-ce298483429f)


## LF 30GHz

Looking now at the 30GHz detectors in the LF tube, the wafer spacing is 128.4mm * 0.00495 deg/mm = 0.63558 deg.  From the pixel center coordinates on the zoom-in we see that the bottom two wafers are at Xi = +/- 0.3181 deg, which agrees within plot resolution.  For each wafer, the pixel spacing should be 18.0mm * 0.00495 deg/mm = 0.0891 deg.  This spacing can be verified on the plots by computing the distance between the center coordinates in degrees.  The FWHM for these detectors is 7.4' = 0.123 deg.  So it makes sense visually that the circles (which are the FWHM) extend about 2/3 the distance to the neighboring pixels.
![lat_f030 pdf](https://github.com/simonsobs/sotodlib/assets/84221/202c6d3e-ec14-41c8-bcb8-9ad802e4ca5b)
![lat_f030_zoom1](https://github.com/simonsobs/sotodlib/assets/84221/7a268709-95f9-4cf1-8956-378364dc8fdc)
![lat_f030_zoom2](https://github.com/simonsobs/sotodlib/assets/84221/7518be3e-b8ff-4159-af61-8db58d31c455)


## MF 90GHz

Looking at the 90GHz detectors, the wafer spacing is again 128.4mm * 0.00495 deg/mm = 0.63558 deg.  The zoom in of this graph is more cluttered, but I checked that this spacing is also true.  For each wafer, the pixel spacing should be 5.3mm * 0.00495 deg/mm = 0.0262 deg.  Also note that the distance across the rhombus gap is equal to the intra-rhombus pixel spacing.  The FWHM for these detectors is 2.2' = 0.037 deg.  So it makes sense visually that the circles (which are the FWHM) overlap with neighboring pixels.
![lat_f090 pdf](https://github.com/simonsobs/sotodlib/assets/84221/9ca8bfa1-e320-4068-b8cd-f203964e7ae0)
![lat_f090_zoom1](https://github.com/simonsobs/sotodlib/assets/84221/376de495-2564-4fbf-b954-5ce964eab74f)
![lat_f090_zoom2](https://github.com/simonsobs/sotodlib/assets/84221/09fe8efc-f3d6-43aa-ab46-faeae701aa2c)


## UHF 230GHz

Moving on to the 230GHz detectors, same wafer spacing of 128.4mm * 0.00495 deg/mm = 0.63558 deg.  Again, hard to read coordinates on the zoomed in view, but I checked this.  The pixel spacing is the same as the MF at 5.3mm * 0.00495 deg/mm = 0.0262 deg.  The FWHM is 1.0' = 0.0167 deg, which matches visually with the plot.
![lat_f230 pdf](https://github.com/simonsobs/sotodlib/assets/84221/01b4fd5f-af88-4c09-8c56-5d551ae6e042)
![lat_f230_zoom1](https://github.com/simonsobs/sotodlib/assets/84221/d92f6951-80ee-4a92-a5b7-cf9fa9a52f6b)


# SAT

For the SAT check I looked at the plots of SAT1.  The wafer spacing is 128.4mm * 0.09668 deg/mm = 12.414 deg.  Along the Xi axis, the center pixels of the hex wafers are indeed very close to this, and the extra ~0.1 degree is due to the ARC projection used in the plot and the large size of the projected focalplane.

## LF 30GHz

The pixel spacing should be 18.0mm * 0.09668 deg/mm = 1.740 deg.  This can be seen directly on the zoomed in plot.  The FWHM is 91.0' = 1.517 degrees, which makes sense visually.
![sat_f030 pdf](https://github.com/simonsobs/sotodlib/assets/84221/4b7fef6f-5280-4395-8afe-c545b122c316)
![sat_f030_zoom1](https://github.com/simonsobs/sotodlib/assets/84221/5b97900e-6c87-4a65-a7fe-f97a9b1f04f5)


## MF 90GHz

The pixel spacing should be 5.3mm * 0.09668 deg/mm = 0.512 deg, which agrees with the plot.  The FWHM is 30.0' = 0.5 degrees, which also makes sense given the plot.
![sat_f090 pdf](https://github.com/simonsobs/sotodlib/assets/84221/933cdfc7-a01f-43a6-bac0-ebace58932d9)
![sat_f090_zoom1](https://github.com/simonsobs/sotodlib/assets/84221/02ddd414-0c29-41f0-a03b-a03c5868cee6)
![sat_f090_zoom2](https://github.com/simonsobs/sotodlib/assets/84221/1f3ff175-36b8-44e0-8868-86c56c0ec61c)


## UHF 230GHz

The pixel spacing should be 5.3mm * 0.09668 deg/mm = 0.512 deg, which agrees with the plot.  The FWHM is 11.0' = 0.183 degrees, which also makes sense given the plot.
![sat_f230 pdf](https://github.com/simonsobs/sotodlib/assets/84221/8acb9451-1fad-4668-bbe3-33d3ce8360b0)
![sat_f230_zoom1](https://github.com/simonsobs/sotodlib/assets/84221/f840cd23-a149-4642-95a0-0149f8050d92)

2023-07-25 21:13 UTC, tskisner commented
Note that the unit tests here (and the code in this branch) will not work before [toast PR 674](https://github.com/hpc4cmb/toast/pull/674) is merged.  Now that this work is ready, I'll get that upstream PR merged.

2023-07-27 14:26 UTC, smsimon approved these changes
These layouts all look correct to me

2023-07-27 14:32 UTC, smsimon commented
One additional question--where is the capability to change individual wafer clockings now?

2023-07-27 20:09 UTC, tskisner commented
About wafer rotation angles within the tube- will push a change for that soon which stores that angle in the hardware dictionary (default to zero).  Will wait until the upstream toast wheel is in place so that tests will run.

2023-07-28 13:15 UTC, mhasself commented
I have reached out on other channels with a question about per-optics tube rotation due to reimaging optics.

2023-07-31 15:17 UTC, mhasself requested changes
As discussed out of band, the on-sky footprint of each optics tube should be "flipped", or rotated by 180 deg.

2023-08-01 21:22 UTC, tskisner commented
The latest changes now implement the wafer rotations outlined in the [Focal Plane Coordinates document](https://simonsobs.atlassian.net/wiki/spaces/PRO/pages/101974017/Focal+Plane+Coordinates) on confluence.  The plots below are now in Xi / Eta sky projection coordinates for easier visual comparison.

## SAT

I used the SAT diagram and theta angles and mapped wafers locations between conventions.  I also used the fact that the `ws2` / `NE` wafer slot has a rotation of "zero", and also the fact that the pin hole in the "A" rhombus is pointing to the "Northwest" at zero theta rotation.  After getting that to match, I applied the optical flip to each tube.  Here are 3 figure showing the progression from (1) all wafers at zero rotation, (2) wafer theta angles to match the figure on the confluence, and (3) the overall flip.
![sat_f090 pdf](https://github.com/simonsobs/sotodlib/assets/84221/8843ef11-f55b-41af-9576-cf5f42d885d5)
![sat_f090 pdf](https://github.com/simonsobs/sotodlib/assets/84221/bb8aa10d-b25f-4bb0-8008-dbb25bde96dc)
![sat_f090 pdf](https://github.com/simonsobs/sotodlib/assets/84221/028d4e2e-b40a-47f4-845f-0dbe25b300f8)

## LAT

Similarly I modeled this after the UFM diagram / table on confluence and the rhombus pin location.  The wafers are rotated so that their pin holes point towards the tube centers.  Here are two figures (1) before the flip and (2) after the flip.
![lat_f090 pdf](https://github.com/simonsobs/sotodlib/assets/84221/34464e58-3c40-4c97-b86d-02bd2ec3ac1c)
![lat_f090 pdf](https://github.com/simonsobs/sotodlib/assets/84221/421a9670-9f6c-4b99-a15e-4062d2da6795)

So just to be clear, the final plot in both cases are with the current code- I was just showing the progression of application of angles to make it easier to see the intermediate steps.

2023-08-09 14:47 UTC, tskisner commented
Ok, this PR was approved in other channels (slack), and the up-to-date plots are now on confluence.  Merging.

2023-08-09 14:48 UTC, merged