Faster glitch flagging
simonsobs/sotodlib pull request #555
Opened 2023-10-05 15:11 UTC by tanaybhandarkar

Based on the discussions in issue #536, I have put in a catch to supply a decimation factor for the Fourier filtered signal if there are over 50,000 samples in the AxisManager. The decimated array will now be around 20,000 samples, which will speed up the `stats.iqr` step.

2023-10-05 15:58 UTC, msilvafe commented
That's great, roughly how much speedup do you get when you still estimate the iqr reasonably?

2023-10-06 01:02 UTC, mhasself requested changes
This is fine except for I don't like "if a: b" and "else: c" on one line!

2023-10-06 01:02 UTC, mhasself commented on sotodlib/flags.py
> +    else: ds = 1
two lines please

2023-10-06 14:08 UTC, tanaybhandarkar commented
> That's great, roughly how much speedup do you get when you still estimate the iqr reasonably? 


Without this adjustment, on a 264000 sample AxisManager, it takes about 60-90s for `get_glitch_flags` to fully run. When adding this downsampling option, it cuts that down to 20s. 

Caveat: There's a lot of variation on the timing, even when running the function without changing anything. I've chalked this up to a simons1 computing quirk. I never saw a 5 min runtime, like you mentioned to me earlier- if you know which context file you were working with, I can test with that one, too.

2023-10-06 16:04 UTC, mhasself approved these changes
Looks good to me but let Max or Katie confirm before merging.

2023-10-06 17:51 UTC, msilvafe commented
Looks good to me I'm happy for you to merge.

2023-10-10 18:51 UTC, merged