Fixes float idxs for scan crossings
simonsobs/sotodlib pull request #568
Opened 2023-10-16 19:13 UTC by jlashner

Many books are failing with this error: 
```
2023-10-16 19:09:08,420: Preprocessing smurf obsid oper_ufm_mv19_1697142674 (INFO)
2023-10-16 19:09:08,467: Preprocessing HK Data (INFO)
Traceback (most recent call last):
  File "/so/home/jlashner/work/book_debugging/main.py", line 15, in <module>
    b.bind()
  File "/so/home/jlashner/repos/sotodlib/sotodlib/io/bookbinder.py", line 778, in bind
    self.preprocess()
  File "/so/home/jlashner/repos/sotodlib/sotodlib/io/bookbinder.py", line 634, in preprocess
    frame_splits = find_frame_splits(self.ancil)
  File "/so/home/jlashner/repos/sotodlib/sotodlib/io/bookbinder.py", line 1089, in find_frame_splits
    return block.times[idxs]
IndexError: arrays used as indices must be of integer (or boolean) type
```

After looking into it I found that these lines are resulting in float arrays instead of ints: https://github.com/simonsobs/sotodlib/blob/9f9b8afc2a2772891ed55a1790f567e9aef23b9d/sotodlib/io/bookbinder.py#L1040-L1042

In particular, this seems to be strange behavior in numpy:
```
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> x = [1, 2, 3]
>>> print(np.array(x).dtype)
int64
>>> print(np.concatenate((x, [])).dtype)
float64
```

Forcing these to be cast back into ints seems to fix the issue, and I've confirmed that books build successfully.

2023-10-16 19:18 UTC, mhasself requested changes
I imagine this is because `array([1])` should obviously become an array of ints but for `array([])` there is not obviously a data type to assume.

Please add a short comment before your additions, for future reader to understand why those are necessary.

2023-10-16 19:27 UTC, jlashner commented
done

2023-10-16 20:20 UTC, skhrg commented
Why not just use the `dtype` parameter in `np.concatenate`?

2023-10-16 20:25 UTC, jlashner commented
@skhrg  np raises this error unless you set `casting='unsafe'`:
```
>>> x = [1, 2, 3]
>>> np.concatenate((x, []), dtype=int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in concatenate
TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'same_kind'
```
The casting type seems like a newish feature of np so I chose to do this instead.

2023-10-16 20:31 UTC, skhrg commented
Oh you probably need `casting='unsafe'` so maybe your method is cleaner then.

2023-10-16 21:23 UTC, kmharrington approved these changes

2023-10-17 13:36 UTC, mhasself approved these changes

2023-10-17 20:34 UTC, merged