Det cuts
simonsobs/sotodlib pull request #624
Opened 2023-12-06 22:17 UTC by msilvafe

Adds in flags function and preprocess support for making detector level cuts based on the IV + bias step results.

2023-12-08 23:14 UTC, msilvafe commented
Ok @kmharrington and @mhasself I have added the changes to change the name from cuts -> flags and wrap a RangesMatrix instead of a boolean mask. I think this is ready for review. Once merged I can run on all observations + create a next context to load in these cuts.

2023-12-09 15:07 UTC, kmharrington approved these changes
My only question is if we want 0.01 or 0.1 to be the minimum acceptable on-transition value. I kind of assume a detector actually at 1% Rn is latched or going to latch very soon.

2023-12-11 15:23 UTC, msilvafe commented
> My only question is if we want 0.01 or 0.1 to be the minimum acceptable on-transition value. I kind of assume a detector actually at 1% Rn is latched or going to latch very soon.

I switched it to 0.1 and will merge after build tests.

2023-12-11 15:53 UTC, mhasself commented on sotodlib/tod_ops/flags.py
> +    merge : bool
psat_range is not documented.  Especially important to say the units.

2023-12-11 16:08 UTC, mhasself commented on sotodlib/tod_ops/flags.py
> +        Boolean mask that selects detector cuts.
Clarify whether True means cut or uncut.

2023-12-11 16:08 UTC, mhasself requested changes
See two doc requests.

2023-12-11 16:58 UTC, msilvafe commented
> See two doc requests.

Ok, I've updated those doc requests. Assuming your happy can you approve those changes? Thanks.

2023-12-11 17:27 UTC, mhasself approved these changes

2023-12-11 17:28 UTC, merged