Change default nperseg behaviour
simonsobs/sotodlib pull request #744
Opened 2024-03-05 23:08 UTC by skhrg

Closes #724 (my first issue!)

2024-03-19 15:12 UTC, mhasself requested changes
So I guess there's no point in making the "50" a parameter for the function, because more likely a user will have a particular frequency resolution in mind?  That's fine.

See requests inline.

2024-03-19 15:12 UTC, mhasself commented on sotodlib/tod_ops/fft_ops.py
> +    By default the nperseg will be set to the base 2 number closest to the 1/50th of
End previous sentence ^^^  with a period.

"base 2 number" -> "power of 2"

2024-03-19 15:12 UTC, mhasself commented on sotodlib/tod_ops/fft_ops.py
> +                              If an nperseg is explicitly passed then that will be used.
Please repair formatting to match other args.

2024-03-19 15:12 UTC, mhasself commented on sotodlib/tod_ops/fft_ops.py
> +    if "npserseg" not in kwargs:
npserseg is a typo.  The punishment for this is usually to make a unit test!

2024-03-26 22:15 UTC, skhrg commented
Requesting permission to fix all the PEP8 issues in the `fft_ops` file in this PR as well.
Also on unit tests, if someone makes a list of ones we want in an issue (or an issue per) I am happy to start banging those out on days like this where site computing is betraying me.

2024-03-27 13:23 UTC, mhasself approved these changes
Fine by me!

I guess it's ok to pep8 the file just before merge... . Make sure it's a dedicated commit, no functional changes, and the commit message is clear that it's "reformatting only".

2024-04-02 20:44 UTC, merged