Pointing workflow
simonsobs/sotodlib pull request #772
Opened 2024-03-19 05:39 UTC by tterasaki

This is a PR for the pointing workflow which I suggested last week.

2026-01-20 23:22 UTC, elle-shaw commented
I will begin to make changes to this code to include true Az/El locations to correspond with each xi-eta detector hit. Before I do that I would like to close out this PR and start fresh.

2026-01-21 19:16 UTC, elle-shaw commented
Nomenclature notes differing between Tomoki's initial PR and now:

1. ``sotodlib.coords.mapbased_pointing.py`` ----------------> ``sotodlib.coords.brightsrc_pointing``
2. ``sotodlib.site_pipeline.make_mapbased_pointing`` ------> ``sotodlib.site_pipeline.get_brightsrc_pointing_step1``
3. ``sotodlib.site_pipeline.update_pointing`` -----------------> ``sotodlib.site_pipeline.get_brightsrc_pointing_step2``
4. ``sotodlib.site_pipeline.combine_focal_planes`` -----------> Not part of this PR

2026-01-28 20:55 UTC, mhasself requested changes
Thanks for pushing this through. I have some documentation and standardization requests.  @msilvafe or @mmccrackan please do sign off on changes to flagman.py and processes.py.

2026-01-28 20:55 UTC, mhasself commented on docs/site_pipeline.rst
> +get_brightsrc_pointing_part1  and  get_brightsrc_pointing_part2
Just make separate entries for these two scripts.  It's ok if only the first one has all the discussion, just say "see part1" in the second one.

2026-01-28 20:55 UTC, mhasself commented on docs/site_pipeline.rst
> +The two-part ``get_brightsrc_pointing`` script set will  will run solve for the xieta
will will

2026-01-28 20:55 UTC, mhasself commented on docs/site_pipeline.rst
> +   :module: sotodlib.site_pipeline.get_brightsrc_pointing_part1  or _part2
This doesn't render ... do separate `argparse::` entries for the two scripts.

2026-01-28 20:55 UTC, mhasself commented on docs/site_pipeline.rst
> +in the time frame. (not recommended)
This is all probably redundant once the `argparse::` block is working properly.

2026-01-28 20:55 UTC, mhasself commented on docs/site_pipeline.rst
> + 2. Fitted xi-eta focal plane position results saved as ResultSet in ``/path/to/results/map_based_results`` as specified in the Step 1 config file. Script will append 'force_zero_roll' onto the speci
Please "fill" long lines so they're ~80 chars wide, matching rest of this file.

2026-01-28 20:55 UTC, mhasself commented on docs/site_pipeline.rst
> +  query_tags: ['moon'=1] #(alternatively specify --sso_name in kwargs)
probably `['moon=1']`, right?

2026-01-28 20:55 UTC, mhasself commented on docs/site_pipeline.rst
> +  wafer_mask_det: 8.  #mask around detector to cut TOD when source too far away.
Is this in degrees?

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +from joblib import Parallel, delayed
This is a new dependency -- add it to `pyproject.toml` in the `[project.optional-dependencies] : site-pipeline` section.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +    print(planet)
turn this into a log message, or remove.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +        tod : An axis manager
"containing a `timestamps` field, which is used to determine the time range and generate the trajectory."

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +        planet (str): The name of the planet for which to generate the trajectory.
This also works for "moon" though right?  Perhaps throw in `e.g. "moon" or "saturn"`.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +    Generate the trajectory of a given planet over a specified time range.
Mention "in horizon coordinates".  az and el are mentioned later, but still.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +import os
Add a preamble comment on the top that these functions are used for fitting detector positions from bright point sources and refer to the site_pipeline scripts that use them.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +    Estimate the rough hit time for a axismanager, wafer_slot, and sso_name.
"Estimate the rough hit time, which is the amount of time for which the source is within some distance from the center of a wafer slot."

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +    Generate boresight-centered maps from Time-Ordered Data (TOD) for each individual detector.
Mention that this modifies `tod` (by messing with focal_plane and boresight).

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +    q_wafer_f = quat.rotation_xieta(-xi_wafer, eta_wafer)
The negative sign here is pretty odd; add a comment about this (and plan to remove it unless we really need it...).

2026-01-28 20:55 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +                xi_det, eta_det, R2_det = -xi_peak, eta_peak, R2
Is the negative sign here the one that cancels out the one we found in line 83?  Comment, cross-ref, plan to fix ...

2026-01-28 20:55 UTC, mhasself commented on sotodlib/site_pipeline/get_brightsrc_pointing_step1.py
> +from sotodlib.site_pipeline import util
this is `utils` now, I believe... if it still works in your test env, it's likely a stale copy of util.py in the install dir.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/site_pipeline/get_brightsrc_pointing_step1.py
> +    parser.add_argument('--min_ctime', type=int, help="Minimum timestamp for the beginning of an observation list")
Our standard is to use `-` rather than `_` in argparser strings.  So `--min-ctime`, and so on.  (Changing them here won't require any changes to main, as argparser naturally puts `--min-ctime` into `args.min_ctime`, which main will get.)

2026-01-28 20:55 UTC, mhasself commented on sotodlib/site_pipeline/get_brightsrc_pointing_step1.py
> +logger = util.init_logger(__name__, 'make_map_based_pointing: ')
Change the log prefix to match script name.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/site_pipeline/get_brightsrc_pointing_step2.py
> +logger = util.init_logger(__name__, 'update_pointing: ')
Change the log prefix to match script name.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/site_pipeline/get_brightsrc_pointing_step2.py
> +        di_rset = np.where(fp_rset['dets:readout_id'] == det)[0][0]
This is what core.util.get_coindices is for ... see also np.intersect1d.  It's fine if simplifying this is not a priority ... just FYI then.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/site_pipeline/get_brightsrc_pointing_step2.py
> +    parser.add_argument('--min_ctime', type=int, help="Minimum timestamp for the beginning of an observation list")
Same request about `-` -> `_` here.

2026-01-28 20:55 UTC, mhasself commented on sotodlib/tod_ops/sub_polyf.py
> -
Revert whitespace changes...
```
git restore --source master sotodlib/tod_ops/sub_polyf.py
git commit -m "revert whitespace changes"
```

2026-01-28 22:07 UTC, msilvafe commented
> Thanks for pushing this through. I have some documentation and standardization requests. @msilvafe or @mmccrackan please do sign off on changes to flagman.py and processes.py.

I'm ok with the changes to flagman but I think the `ReduceFlags` process could be absorbed into `CombineFlags` which already handles arbitrary combinations of `union` and `intersection` so you just need to add in handling for the new `except` method.

2026-01-28 22:34 UTC, iparask commented on sotodlib/coords/brightsrc_pointing.py
> +from joblib import Parallel, delayed
This is not used. I suggest to remove it.

2026-01-28 22:45 UTC, iparask commented on sotodlib/site_pipeline/get_brightsrc_pointing_step1.py
> +        )
Since this is running under slurm, instead of using the joblib Parallel, you can use the MPI or multiprocess executor. You can do:

```python
rank, executor, as_completed_callable = get_exec_env(nprocs=n_jobs)
futures = [executor.submit(
            main_one_wafer,
                configs=configs,
                obs_id=obs_id,
                wafer_slot=wafer_slot,
                sso_name=sso_name,
                restrict_dets_for_debug=restrict_dets_for_debug,
            )
            for wafer_slot in processed_wafer_slots]
for future in as_completed_callable(futures):
     # you can print what you want here
```

2026-01-28 22:46 UTC, iparask commented on sotodlib/site_pipeline/get_brightsrc_pointing_step2.py
> +        )
Same as above

2026-01-30 22:30 UTC, elle-shaw commented on docs/site_pipeline.rst
> +  wafer_mask_det: 8.  #mask around detector to cut TOD when source too far away.
yes

2026-02-12 17:00 UTC, elle-shaw commented on sotodlib/site_pipeline/get_brightsrc_pointing_step1.py
> +        )
I tested this out, and it looks like the code moved on to finishing the rest of the script and saving the results before the parallel jobs had completed. Here is a peek at the output log.



submitted map job
   0.175: Processing obs_1770708340_satp2_1111111 (INFO)
  14.530: hit_time for ws0 is 1863.2 [sec] (INFO)
  15.549: hit_time for ws1 is 1450.4 [sec] (INFO)
  16.502: hit_time for ws2 is 1328.6 [sec] (INFO)
  17.444: hit_time for ws3 is 2964.6 [sec] (INFO)
  18.406: hit_time for ws4 is 363.1 [sec] (INFO)
  19.392: hit_time for ws5 is 456.5 [sec] (INFO)
  20.355: hit_time for ws6 is 1331.8 [sec] (INFO)
  20.357: Found saved data for these wafer_slots: [] (INFO)
  20.358: Will continue for these wafer_slots: ['ws0', 'ws1', 'ws2', 'ws3', 'ws6'] (INFO)
  20.358: Continuing with parallel job (INFO)
  20.358: Entering wafer pool (INFO)
  20.474: create dummy hdf for non-hitting wafer: ['ws4', 'ws5'] (INFO)
  23.560: making combined result (INFO)
  23.628: ta da! Finished with obs_1770708340_satp2_1111111 (INFO)
   0.066: loading meta data: ws0 (INFO)
   0.067: loading meta data: ws1 (INFO)
   0.058: loading meta data: ws2 (INFO)
   0.061: loading meta data: ws6 (INFO)
   0.065: loading meta data: ws3 (INFO)
   1.541: finished loading meta data: ws2 (INFO)
   1.541: loading tod data: ws2 (INFO)
   1.548: finished loading meta data: ws3 (INFO)
   1.548: loading tod data: ws3 (INFO)
   1.629: finished loading meta data: ws1 (INFO)

2026-02-12 17:11 UTC, elle-shaw commented on sotodlib/site_pipeline/get_brightsrc_pointing_step1.py
> +        )
In case this isn't clear:

The job started creating the dummy wafers  (for which there was not any hit time from the moon) and then created a full focal plane  combined result without the moon-hit wafers that needed to get processed. They did get processed and saved, but after the combined result had already been made. 

I can recover the results because the code searches the output directory for existing individual wafer results, and picks up where it left off, always creating a new combined full focal plane .h5 file. 
So running the code a second time this morning, it does this and I can see the data. But I don't want to have to run it twice, so how can I make it wait for the MPI job to finish before making the combined result?

2026-02-17 00:06 UTC, elle-shaw commented on sotodlib/coords/brightsrc_pointing.py
> +                xi_det, eta_det, R2_det = -xi_peak, eta_peak, R2
I'm still looking into this part

2026-02-18 01:22 UTC, elle-shaw commented on sotodlib/coords/brightsrc_pointing.py
> +                xi_det, eta_det, R2_det = -xi_peak, eta_peak, R2
I don't think it undoes what is going on in line 83.  I'm not sure about this one yet.

2026-02-25 00:18 UTC, elle-shaw commented on sotodlib/coords/brightsrc_pointing.py
> +                xi_det, eta_det, R2_det = -xi_peak, eta_peak, R2
I think I figured this out. All the `quat.rotation_lonlat` commands are defined with +AZ instead of -1*Az.  When I went through and changed every quaternion  in boresight_pointing.py to have -1*Az in the q_planet and q_bs,  and reverted these two places with the weird negative signs, I get the same result out as before. So for the sake of pointing practices, I will correct these.

2026-03-25 20:47 UTC, elle-shaw commented
My latest changes to `get_brightsrc_pointing_step2` save the median the az, el, and roll of the SAT boresight from the time when each detector observed the source object. Changes to `finalize_focal_plane` and `fp_containers' is so the az, el, and roll data is passed correctly into a FocalPlane object so the data can be accessed when fed into the pointing model solving code.

2026-03-26 15:07 UTC, skhrg reviewed
Only reviewing the focal plane changes for now. Looks good to me, just one minor question.

2026-03-26 15:07 UTC, skhrg commented on sotodlib/coords/fp_containers.py
> +        roll = np.nan + np.zeros_like(eta)
Why not default to the average values from the TOD/obsinfo? That way down the line you don't need any branching where you see if these are nans and then pull that info from the TOD/obsinfo.

2026-03-26 15:07 UTC, skhrg commented on sotodlib/site_pipeline/finalize_focal_plane.py
> +
Whitespace

2026-04-22 20:58 UTC, mhasself requested changes
Ok, last minor comments.

2026-04-22 20:58 UTC, mhasself commented on docs/site_pipeline.rst
> +-------------------
Why do the part1/part2 docs straddle make_read_det_match?

2026-04-22 20:58 UTC, mhasself commented on sotodlib/coords/brightsrc_pointing.py
> +#from joblib import Parallel, delayed
remove commented import

2026-04-22 20:58 UTC, mhasself commented on sotodlib/coords/fp_containers.py
>              raise ValueError("full_fp or tot_weight not initialized")
Error message also needs update?

2026-04-22 20:58 UTC, mhasself commented on sotodlib/preprocess/processes.py
> +import pdb
remove this import?

2026-04-23 00:38 UTC, elle-shaw commented on docs/site_pipeline.rst
> +-------------------
Hmm. maybe that happened during a merge and I missed it. Fixed now.

2026-04-23 07:43 UTC, mhasself approved these changes

2026-04-23 17:10 UTC, merged