added focal_plane nan checker in coords.pmat.for_tod
simonsobs/sotodlib pull request #775
Opened 2024-03-21 01:57 UTC by tterasaki

https://github.com/simonsobs/sotodlib/issues/763

2024-03-21 13:09 UTC, mhasself commented on sotodlib/coords/pmat.py
> +
gamma is allowed to be None here, which I think will cause the array promotion of [xi, eta, gamma] to fail.

Simpler logic uses `if np.any(np.isnan(...))`.

2024-03-21 13:10 UTC, mhasself requested changes

2024-03-21 13:10 UTC, mhasself commented on sotodlib/coords/pmat.py
> +
gamma is allowed to be None here, which I think will cause the array promotion of [xi, eta, gamma] to fail.

Simpler logic uses `if np.any(np.isnan(...))`.

2024-04-03 01:55 UTC, tterasaki commented
Thanks Matthew and sorry for the late reply.
I think it is ready to merge.

2024-04-03 14:31 UTC, mhasself commented
> Thanks Matthew and sorry for the late reply. I think it is ready to merge.

No prob -- but see my comment about "gamma".  It can be None.  This code will choke on that.

2024-04-25 16:07 UTC, kmharrington commented
When will this converge for merging? Enough other people are hitting this issue and solving it (ex: https://github.com/simonsobs/sotodlib/pull/816 ) that we need to have the nice version in master

2024-04-26 02:42 UTC, mhasself commented
I am sorry this is so much fun, but I think you need to also add this:
```
        if gamma is not None and np.any(np.isnan(gamma)):
            raise ValueError('np.nan is included in gamma')
```

2024-04-26 04:13 UTC, mhasself approved these changes
To infinity and beyond!

2024-04-26 04:13 UTC, merged