Generalize outside data paths
simonsobs/sotodlib pull request #817
Opened 2024-04-22 19:52 UTC by iparask

This PR closes #813.

It introduces an environment variable for data that are downloaded. This variable is a serialized JSON.

This is a breaking change since it will raise a runtime error when the environment variable does not have the expected entry.

We may want to merge it along with an addition to soconda module file that set the variable.

2024-04-25 15:56 UTC, kmharrington commented
@jlashner  you had a different environmental variable name for site pipeline things?

2024-04-25 20:59 UTC, iparask commented
@kmharrington, @jlashner, the more we add to this env variable the better I think.

2024-04-25 21:03 UTC, jlashner commented
In certain scripts I allow the usage of the env var `SITE_PIPELINE_CONFIG_DIR` to specify the config dir root, which is useful during local testing, but that seems pretty unrelated to what you're adding! I don't know if they need to be merged right now.

2024-04-26 02:05 UTC, mhasself commented
Thanks for contribution -- but please undo the major reformatting.

It is long-standing policy that:
- bulk reformatting should be done in separate commits, and preferably separate PRs, from substantive changes.
- bulk reformatting should only be done when necessary.

I'll have some comments on the substance too but might as well get this part handled!

2024-04-26 02:15 UTC, mhasself requested changes
On the substance --

1) the decoding you added in _get_astrometric can be made more general.  Move it into new submodule, `core.resources`, and have _get_astrometric simply call that('de421.bsp') to get a path.
2) I would like to leave a hard-coded dictionary in sotodlib, to name all the useful files (which will expand beyond this 1 ephemeris) and provide standard places to grab them from.  The soconda installer can use that to populate the cache.  (This was the original intention behind RESOURCE_URLS declared at top-level in planets.py)  I don't want to require that esoteric envvars be required by default.  Most installations of sotodlib do not use soconda.
3) The envvar can then be _entirely optional_, meaning that if "de421.bsp" is not listed in the decoded SOTODLIB_RESOURCES, the code will instead grab the spec from the core.resources.RESOURCE_DEFAULTS dict and use that.

Makes sense?

2024-05-02 14:15 UTC, iparask commented
@mhasself, I think it is ready for a new review.

2024-05-13 13:53 UTC, mhasself requested changes
Thank -- couple comments on the implementation, mostly documentation.

2024-05-13 13:53 UTC, mhasself commented on sotodlib/coords/planets.py
> +            f'Failed to find a match for "{source_name}" in ' f"ephemeris: {options}"
Please reformat this mangled string

2024-05-13 13:53 UTC, mhasself commented on sotodlib/coords/planets.py
> +            }
Restore newline at eof.

2024-05-13 13:53 UTC, mhasself commented on sotodlib/core/resources.py
> +             cache them after a download
This is not accurate.

2024-05-13 13:53 UTC, mhasself commented on sotodlib/core/resources.py
> +            + "local path or an ftp path."
All resources should be listed in RESOURCE_DEFAULTS, so that should be the primary instruction to the use in this (helpful) error message.

2024-05-13 13:53 UTC, mhasself commented on sotodlib/core/resources.py
> +
Add `else` block to handle malformed de_url.

2024-05-13 13:53 UTC, mhasself commented on sotodlib/core/resources.py
> +    from an ftp path.
In docstring, explain the path search order.  Provide an example of a well-formed SOTODLIB_RESOURCES var.

2024-06-13 19:47 UTC, iparask commented
@mhasself can you take another look? Thank you!

2024-06-14 02:52 UTC, mhasself approved these changes
Thanks!

2024-07-08 14:43 UTC, merged