Do not set turnarounds as invalid by default
simonsobs/sotodlib pull request #886
Opened 2024-06-10 19:02 UTC by keskitalo

2024-06-10 23:49 UTC, tskisner requested changes
The main thing I see from this PR is that the upstream toast non-science shared mask should include the processing bit (surprised that it does not actually).  But the other changes seem to be unnecessary with current defaults.  Happy to chat offline tomorrow and figure out what is going on.

2024-06-10 23:49 UTC, tskisner commented on sotodlib/toast/workflows/proc_mapmaker.py
> +            shared_flag_mask=3,
The default shared flag mask for the BinMap operator is to [cut all "non-science" data](https://github.com/hpc4cmb/toast/blob/697eefd199d61c25c082535078875bd3973256bf/src/toast/ops/mapmaker_binning.py#L83).  The hard-coded value here is equivalent to including the `processing` bit (which I agree with) and excluding the `irregular` and `unstable_scanrate` bits (why?).  It looks like we should actually change the meaning of the non-science flag in toast to include processing bit (which it does for the detector mask).

If you need a temporary workaround here in sotodlib, could we do something like
```
shared_flag_mask=(defaults.shared_mask_nonscience | defaults.shared_mask_processing)
```
to make it more clear the names of the flag bits?

2024-06-10 23:49 UTC, tskisner commented on sotodlib/toast/workflows/proc_mapmaker.py
> +            shared_flag_mask=3,
Similarly for this.

2024-06-10 23:49 UTC, tskisner commented on sotodlib/toast/workflows/sim_observe.py
> +            turnaround_mask=2,
The current defaults in the `SimGround` operator [set the turnarounds to "unstable_scanrate"](https://github.com/hpc4cmb/toast/blob/697eefd199d61c25c082535078875bd3973256bf/src/toast/ops/sim_ground.py#L301) (equivalent to `4`, not invalid).  The defaults of the `SimAtmosphere` operator [is to use the invalid mask](https://github.com/hpc4cmb/toast/blob/697eefd199d61c25c082535078875bd3973256bf/src/toast/ops/sim_tod_atm.py#L81) (equivalent to `1`).  So I don't see any conflict in the default flagging...

Is it possible there is a stale config somewhere with hardcoded flag values that is interfering with the defaults?

2024-06-11 07:02 UTC, keskitalo commented
This branch has been rendered obsolete by changes in TOAST defaults.

2024-06-11 07:02 UTC, closed without merging