hwp angle model metadata
simonsobs/sotodlib pull request #915
Opened 2024-08-05 16:30 UTC by ykyohei

This PR adds new hwp_angle_model metadata.
hwp_angle_model metadata is for tracking the version of hwp_angle_model, it does not add new functionality to apply_hwp_angle_model. site_pipeline.make_hwp_angle_model.py is a script that will generate hwp_angle_model metadata and we will manage the version manually.

I think there can be a much better implementation of versioning hwp_angle_model or make_hwp_angle_model.py, so I start this PR as a draft. For example, versioning a yaml file or text file seems sufficient for this? I would appreciate any suggestions.

We have to merge this PR and update use_this.yaml at the same time.
My plan of merging procedure is to make a hwp_angle_model metadata in my local directory and ask admin to copy metadata files to the shared directory in site-computing.
Then, we wait until hwp_angle_model metadata is synced to NERSC etc.
Finally, we merge this PR and update the use_this.yaml at site-computing.

2024-08-09 22:55 UTC, ykyohei commented
Addressed suggestions. PR for the scripts for hwp_angle_model is https://github.com/simonsobs/pipeline-metadata-scripts/pull/1
@17-sugiyama I would appreciate if you could doble check.

2024-08-24 20:59 UTC, mhasself requested changes
Great!  Just a couple edits to concord with my suggestions in response to https://github.com/simonsobs/pipeline-metadata-scripts/pull/1

2024-08-24 20:59 UTC, mhasself commented on sotodlib/hwp/hwp_angle_model.py
> +    model.wrap('sign_dependent_offset', np.deg2rad(-1. * 360 / 1140 * 3 / 2))
add `'model_version'`

2024-08-24 20:59 UTC, mhasself commented on sotodlib/hwp/hwp_angle_model.py
`assert model.model_version == 'v2'`

2024-08-28 17:10 UTC, ykyohei commented
Done and tested it!

2024-08-28 17:45 UTC, mhasself approved these changes
Great, thanks!

2024-08-28 17:50 UTC, merged