Adds `force_pointing` kw to match_params
simonsobs/sotodlib pull request #924
Opened 2024-08-12 15:14 UTC by jlashner

- New `force_pointing` match param that will make it so only detectors with pointing information are matched.
- Removes the `force_src_pointing` param (which would force a match if pointing is provided) since this was always buggy and never had good results
- Allows you to set resonator pointing from the `ResSet.from_aman` function.

2024-09-06 14:50 UTC, mhasself requested changes
As discussed I think a more complete matching rule for incorporating _strict position info_ would need to consider the detector type:

- NC: do not match (these don't have design_freq anyway)
- DARK, SLOT: _may or may not_ have position meas.
- UNRT, SQID, BARE: _must not_ have position meas.
- OPTC: _must_ have position meas.

2024-09-09 21:52 UTC, jlashner commented
Alright, I added different pointing checks that depend on the det-type like you described above, and confirmed that it still works and that I still get good matches. Info on the new match solutions + plots are here: https://simonsobs.atlassian.net/wiki/x/RwC2JQ

I also changed the config option from `force_pointing` to `enforce_pointing_reqs`.

2024-09-16 14:50 UTC, mhasself requested changes
Also remove .vscode files!

2024-09-16 14:50 UTC, mhasself commented on sotodlib/coords/det_match.py
> +    ])
I think you are looking for `np.isin`!

2024-09-16 14:50 UTC, mhasself commented on sotodlib/coords/det_match.py
> +        if self.match_pars.enforce_pointing_reqs:
So in this block, 'DARK' and 'SLOT' are implicitly untouched.  I think you need to at least _comment on_ DARK/SLOT, if not check explicitly that everything you haven't directly modified is listed as DARK or SLOT.

2024-10-01 18:14 UTC, jlashner commented
Hi @mhasself, I think I addressed your feedback so this is ready for a re-review when you can!

2024-10-30 20:34 UTC, mhasself approved these changes
Sorry this fell off my radar.  Please squash on merge.  Thanks!

2024-10-30 20:36 UTC, merged